program.close.title=Close Program
program.close.message=Exit the program
program.close.prompt=Are you sure you wan to exit?
no-tool-for-resource-message=No tool for resource: {0}
no-tool-for-resource-title=No Tool
task-error-message=A {0} occurred while running the {1}.
resource-unable-to-resolve=Cannot resolve resource URI: {0}
resource-modified=Modifed Resources
resource-modified-message=There are unsaved modified resources
resource-modified-prompt=Do you want to save them?
program-hidpi-title=HiDPI Support
program-hidpi-message=This screen appears to support HiDPI. Consider enabling application scaling by setting the Gnome scaling-factor:\n\ngsettings set org.gnome.desktop.interface scaling-factor 2
resource-not-found=Resource not found: {0}
resource-error-list=Error getting resource list: {0}
resource-error=Error opening {0}
help-document-not-found=Help document not found!
error-loading-help-content=Error loading help content!
ui-restore-error-title=Error restoring the workspace
resource-missing=Resource missing: {0}
tool-missing=Tool missing: {0}
ui-restore-error-default-view=The default view was not restored. This will cause a workspace problem.
program-linux-no-pkexec-title=PkExec Not Installed
program-linux-no-pkexec-message=It appears you are running a Linux distribution but PkExec is not installed. Consider installing the pkexec package for your distribution.

