product-name=Products
product-description=Program product resource type

about-name=About
about-description=Program about resource type

guide-name=Guide
guide-description=Program guide resource type

settings-name=Settings
settings-description=Program settings resource type

welcome-name=Welcome
welcome-description=Program welcome resource type

task-name=Tasks
task-description=Program tasks resource type

resources=Resources
close-save-prompt=Do you want to save the file before closing it?
close-save-title=Close
close-save-message=Save file
help-name=Help
help-description=Program help resource type

notice-name=Notice
notice-description=Product notice resource type
fault-name=Fault
fault-description=A program fault
resource-new-name=New Resource
resource-new-description=Create a new program resource
resource-open-name=Open Resource
resource-open-description=Open a program resource
resource-open-folder-size={0} items
themes-name=Themes
themes-description=Program themes resource type
properties-name=Properties
properties-description=The properties of an object
resource-type-not-supported=Resource type not supported: {0}
index-search-name=Index Search
resource-missing=Resource Missing
resource-is-missing=Unable to find {0}\n\nURI: {1}
