workspace-close-title=Close Window
workspace-close-message=Close the window
workspace-close-prompt=Are you sure you wan to close the window?
workspace-open-in=Open Workarea
workspace-open-in-message=Open workarea in current window or a new window?
workspace-open-in-prompt=Choose where to open the workarea:
workspace-open-in-current=Current Window
workspace-open-in-new=New Window
search-no-results=No results
